/**
 * Condition & prescriber-review advice rules (non-medication).
 * Medication absolute rules live in medications-absolute.data.js
 *
 * @module advice/rules/conditions
 */
window.EDM_ADVICE_RULES = window.EDM_ADVICE_RULES || {};

window.EDM_ADVICE_RULES.conditions = [
  {
    id: 'ORL-01',
    title: 'Chronic Malabsorption',
    tab: 'absolute',
    tabLabel: 'Absolute',
    action: 'REJECT',
    summary: 'Reject. SPC §4.3 absolute contraindication — fat absorption is already impaired; orlistat adds compound malabsorption.',
    source: 'Xenical/Alli SPC §4.3; NICE CKS; consultation §6.2',
    rejectIf: [
      'Chronic malabsorption syndrome (documented)',
      "Crohn's with significant small-bowel disease, short bowel, uncontrolled coeliac",
    ],
    rationale: 'Orlistat inhibits lipases and reduces dietary fat absorption (~30%). In chronic malabsorption the mucosa is already compromised — adding pharmacological malabsorption risks severe fat-soluble vitamin deficiency (A, D, E, K). Listed explicitly in SPC §4.3.',
    searchTags: ['crohn', 'coeliac', 'short bowel', 'malabsorption', 'bariatric', 'gastric bypass', 'sleeve gastrectomy', 'gastric sleeve', 'roux-en-y', 'biliopancreatic', 'pancreatic insufficiency'],
  },
  {
    id: 'ORL-02',
    title: 'Cholestasis',
    tab: 'absolute',
    tabLabel: 'Absolute',
    action: 'REJECT',
    summary: 'Reject. SPC §4.3 absolute contraindication — bile-dependent fat digestion is impaired; orlistat is ineffective and may worsen hepatobiliary status.',
    source: 'Xenical/Alli SPC §4.3; consultation §6.2',
    rejectIf: [
      'Active cholestasis (intra- or extrahepatic)',
      'Obstructive jaundice, PBC flare, ICP, biliary obstruction',
    ],
    rationale: 'Orlistat requires bile-salt emulsification of dietary fat before lipase inhibition can reduce absorption. Without adequate bile delivery, orlistat has no substrate and adds fat malabsorption on top of impaired bile-acid cycling.',
    searchTags: ['cholestasis', 'jaundice', 'pbc', 'cholangitis', 'bile acid malabsorption'],
  },
  {
    id: 'ORL-03',
    title: 'Breastfeeding',
    tab: 'absolute',
    tabLabel: 'Absolute',
    action: 'REJECT',
    summary: 'Reject while breastfeeding. SPC §4.3 contraindication — excretion in breast milk is unknown.',
    source: 'Xenical/Alli SPC §4.3; consultation §6.2',
    rejectIf: ['Currently breastfeeding or expressing for infant feeding'],
    rationale: 'SPC states orlistat is contraindicated during breast-feeding because it is not known whether orlistat is secreted into human milk. Maternal fat-soluble vitamin depletion may also affect milk quality.',
    searchTags: ['breastfeeding', 'lactation', 'nursing', 'breast feed', 'breast-feed'],
  },
  {
    id: 'ORL-04',
    title: 'Hypersensitivity',
    tab: 'absolute',
    tabLabel: 'Absolute',
    action: 'REJECT',
    summary: 'Reject if allergy to orlistat or excipients. SPC §4.3 contraindication; anaphylaxis and angioedema reported.',
    source: 'Xenical/Alli SPC §4.3; consultation §6.2',
    rejectIf: ['Documented allergy to orlistat or capsule excipients (e.g. gelatin)'],
    rationale: 'Standard pharmacological contraindication per SPC §4.3. Re-challenge after serious hypersensitivity is contraindicated.',
    searchTags: ['allergy', 'anaphylaxis', 'angioedema', 'orlistat allergy'],
  },
  {
    id: 'ORL-05',
    title: 'Pregnancy',
    tab: 'absolute',
    tabLabel: 'Absolute',
    action: 'REJECT',
    summary: 'Reject if pregnant or planning pregnancy. SPC §4.6: not recommended (Alli §4.3 contraindication); nutritional concerns predominate.',
    source: 'Xenical SPC §4.6; Alli SPC §4.3; NICE CKS; consultation §6.2',
    rejectIf: [
      'Confirmed or suspected pregnancy',
      'Trying to conceive or intending pregnancy during treatment',
    ],
    rationale: 'No adequate human pregnancy data. Orlistat reduces fat and fat-soluble nutrient absorption — inappropriate during pregnancy. Xenical §4.6 advises caution and recommends against use; Alli lists pregnancy in §4.3 contraindications.',
    searchTags: ['pregn', 'conception', 'gestation', 'gravid'],
  },
  {
    id: 'ORL-06',
    title: 'History or Active Eating Disorder',
    tab: 'absolute',
    tabLabel: 'Absolute',
    action: 'REJECT',
    summary: 'Reject. Not an SPC contraindication, but NICE NG246 requires eating disorders to be considered and consultation §6.2 screens out any history of anorexia/bulimia.',
    source: 'NICE NG246 §1.1.1; consultation §6.2; safeguarding (EDM-WM-01 §12)',
    rejectIf: [
      'Active or historical anorexia nervosa or bulimia (consultation answer = Yes)',
      'ARFID or formal binge-eating disorder',
    ],
    conditions: [
      'Anorexia nervosa',
      'Bulimia nervosa',
      'Binge Eating Disorder (BED)',
      'Avoidant/Restrictive Food Intake Disorder (ARFID)',
    ],
    rationale: "SPC does not list eating disorders, but NICE NG246 mandates consideration of current or previous eating disorders before weight-management medicines. Orlistat's GI effects can reinforce restriction or purging. EveryDayMeds consultation requires 'No' to eating-disorder history; apply safeguarding pathway if flagged on SCR.",
    searchTags: ['anorexia', 'bulimia', 'arfid', 'binge', 'eating disorder', 'avoidant restrictive'],
  },
  {
    id: 'ORL-07',
    title: 'Type 2 Diabetes',
    tab: 'prescriber-review',
    tabLabel: 'Prescriber review',
    action: 'REVIEW',
    summary: 'T2DM supports eligibility at BMI ≥28. Metformin is acceptable — reject only if on insulin or sulfonylurea (Med — absolute).',
    source: 'Xenical SPC §4.1, §4.4; NICE CKS; NICE NG246; consultation §6.2',
    askPatient: ['Current antidiabetic agents', 'Recent HbA1c'],
    rejectIf: [
      'On insulin or sulfonylurea (med-absolute entries)',
      'Uncontrolled hyperglycaemia requiring urgent optimisation first',
    ],
    acceptIf: [
      'On metformin only, or diet-controlled',
      'BMI and comorbidity criteria met; GP aware',
    ],
    rationale: 'Type 2 diabetes is a licensed qualifying comorbidity at BMI ≥28. Metformin does not cause hypoglycaemia and does not require proactive dose reduction as weight falls — patients on metformin alone may proceed with GP awareness documented. Insulin and sulfonylureas are excluded: weight loss on orlistat improves insulin sensitivity and can cause hypoglycaemia if those doses are not reduced first (SPC §4.4).',
    searchTags: ['type 2 diabetes', 't2dm', 'diabetes mellitus type 2', 'hba1c', 'niddm'],
    excludeTags: ['type 1 diabetes', 't1dm', 'insulin dependent'],
  },
  {
    id: 'ORL-08',
    title: 'Chronic Kidney Disease',
    tab: 'prescriber-review',
    tabLabel: 'Prescriber review',
    action: 'REVIEW',
    summary: 'Prescribe with caution per NICE CKS. SPC §4.4: hyperoxaluria/oxalate nephropathy risk, increased with CKD or volume depletion.',
    source: 'Xenical SPC §4.4; NICE CKS',
    askPatient: ['Latest eGFR', 'Stone history', 'Hydration status'],
    rejectIf: ['Dialysis', 'eGFR <30 with active stone disease', 'Acute kidney injury'],
    acceptIf: ['eGFR ≥30, stable, well hydrated', 'Multivitamin at bedtime; GP aware'],
    rationale: 'Not an SPC contraindication, but SPC §4.4 and NICE CKS warn orlistat may cause hyperoxaluria and oxalate nephropathy — risk is higher with underlying CKD. Consultation §6.2 also screens out declared kidney problems.',
    searchTags: ['ckd', 'chronic kidney', 'renal', 'egfr', 'kidney stones', 'nephropathy', 'dialysis', 'nephrectomy', 'polycystic kidney'],
  },
  {
    id: 'ORL-09',
    title: 'Hepatic Impairment',
    tab: 'prescriber-review',
    tabLabel: 'Prescriber review',
    action: 'REVIEW',
    summary: 'Review severity. Cholestasis/cirrhosis → absolute reject. Stable MASLD/NAFLD may benefit from weight loss; MHRA: rare hepatic injury reported.',
    source: 'Xenical SPC §4.4; MHRA; NICE CKS',
    askPatient: ['Diagnosis (MASLD vs cirrhosis vs hepatitis)', 'LFT trend'],
    rejectIf: ['Active cholestasis', 'Cirrhosis', 'Acute hepatitis', 'End-stage liver disease'],
    acceptIf: ['Stable MASLD/NAFLD without cholestasis', 'Mild transaminitis improving with weight-loss plan'],
    rationale: 'Hepatic impairment has not been studied (SPC). Rare serious hepatic injury reported post-marketing. Cholestasis remains §4.3 absolute. MASLD is a common qualifying comorbidity where weight loss is beneficial.',
    searchTags: ['nafld', 'masld', 'fatty liver', 'hepatitis', 'hepatic fibrosis', 'liver transplant', 'end stage liver'],
    priorityTags: ['cirrhosis', 'cholestasis'],
  },
  {
    id: 'ORL-10',
    title: 'Gallbladder Removal',
    tab: 'prescriber-review',
    tabLabel: 'Prescriber review',
    action: 'REVIEW',
    summary: 'Reject if <12 months post-cholecystectomy (service policy). After ≥12 months: assess bile-acid diarrhoea before proceeding.',
    source: 'EveryDayMeds policy (aligned GLP-1 §9.8); SPC GI warnings §4.4',
    askPatient: ['Date of surgery', 'Post-cholecystectomy GI symptoms'],
    rejectIf: [
      'Cholecystectomy within 12 months',
      'Active bile-acid diarrhoea or steatorrhoea',
    ],
    acceptIf: [
      'Surgery ≥12 months ago with manageable GI function',
      'Patient counselled on additive GI side effects',
    ],
    rationale: 'Not an SPC contraindication, but altered bile dynamics after cholecystectomy can compound orlistat GI effects. EveryDayMeds applies a 12-month post-surgical exclusion consistent with GLP-1 policy. Consultation §6.2 screens out cholecystectomy.',
    searchTags: ['cholecystectomy', 'cholecyst', 'gallbladder removal', 'gallbladder', 'post-chole', 'cholelithiasis', 'gallstone'],
    timeSensitive: {
      monthsThreshold: 12,
      rejectIfWithinMonths: true,
      eventLabel: 'cholecystectomy / gallbladder surgery',
    },
  },
  {
    id: 'ORL-11',
    title: 'Untreated Secondary Obesity',
    tab: 'prescriber-review',
    tabLabel: 'Prescriber review',
    action: 'REVIEW',
    summary: 'Treat the cause first. Orlistat is ineffective if weight gain is from untreated hypothyroidism, Cushing\'s, or unaddressed weight-promoting medicines.',
    source: 'NICE NG246 §1.1.1; NICE CG189',
    askPatient: ['TSH', 'Steroid/antipsychotic weight-promoting medicines', 'Endocrine symptoms'],
    rejectIf: [
      'Untreated hypothyroidism (raised TSH)',
      'Active Cushing\'s or untreated secondary obesity',
    ],
    acceptIf: [
      'Thyroid optimised — but levothyroxine is an excluded medicine (§6.2); reject if on thyroid replacement',
      'Underlying cause addressed or specialist agrees to proceed',
    ],
    rationale: 'NICE requires medicines and conditions affecting weight to be considered before pharmacotherapy. Untreated hypothyroidism causes weight gain via mechanisms orlistat does not address.',
    searchTags: ['hypothyroid', 'cushing', 'addison', 'graves', 'overactive thyroid', 'acromegaly', 'prolactin', 'pituitar'],
  },
  {
    id: 'ORL-26',
    title: 'Weight-Loss Injections (Mounjaro, Wegovy)',
    tab: 'med-review',
    tabLabel: 'Med — review',
    action: 'REVIEW',
    summary: 'Reject only if overlapping concurrent supply. A single established GLP-1 on the repeat list (GP aware) is acceptable.',
    source: 'NICE CG189 §1.9; consultation §6.2',
    rejectIf: [
      'Overlapping supply — GLP-1/GIP agonist on both repeat and acute medication lists (two sources)',
      'Two different weight-loss injections active at once (e.g. Mounjaro and Wegovy)',
      'Multiple concurrent acute supplies suggesting duplicate sourcing',
    ],
    acceptIf: [
      'Single established supply on repeat medication list only — GP notified and documented on SCR',
      'No second GLP-1 source on acute or repeat lists',
    ],
    rationale:
      'NICE CG189 prohibits concurrent weight-reduction medicines. Mounjaro or Wegovy on the repeat list alone means the GP is already supplying it — that is not a contraindication unless a second overlapping supply appears elsewhere on the SCR.',
    searchTags: ['glp-1', 'glp1', 'wegovy', 'mounjaro', 'saxenda', 'semaglutide', 'tirzepatide', 'liraglutide', 'ozempic', 'rybelsus', 'mysimba', 'pramlintide', 'symlin', 'flextouch', 'nevolat'],
    priorityTags: ['wegovy', 'mounjaro', 'semaglutide', 'tirzepatide', 'liraglutide', 'saxenda', 'ozempic'],
  },
  {
    id: 'ORL-27',
    title: 'Oral Contraceptive Pill',
    tab: 'med-review',
    tabLabel: 'Med — review',
    action: 'REVIEW',
    summary: 'Not a contraindication. SPC §4.4: advise backup contraception if severe diarrhoea (OCP absorption may fall).',
    source: 'Xenical/Alli SPC §4.4',
    askPatient: ['OCP brand', 'Willingness to use backup method'],
    acceptIf: [
      'Patient counselled on backup contraception during diarrhoea episodes',
      'Not pregnant or planning pregnancy',
    ],
    rationale: 'Specific drug-interaction studies showed no interaction, but SPC §4.4 recommends an additional contraceptive method if severe diarrhoea occurs because OCP absorption may be indirectly reduced.',
    searchTags: ['contraceptive', 'ocp', 'oral contraceptive', 'microgynon', 'rigevidon', 'cilest', 'yasmin'],
  },
  {
    id: 'ORL-28',
    title: 'Depression and Mental Health',
    tab: 'prescriber-review',
    tabLabel: 'Prescriber review',
    action: 'REVIEW',
    rejectIf: [
      'Active suicidal ideation or self-harm',
      'Acute psychiatric deterioration or crisis',
      'Unstable depression or anxiety requiring urgent mental health input',
    ],
    acceptIf: [
      'Mental health stable and appropriately supported',
      'No safeguarding concerns',
      'GP or mental health team aware if on psychiatric treatment',
    ],
    conditions: [
      'Depression',
      'Anxiety',
      'Generalised anxiety disorder',
      'Mixed anxiety and depression',
      'Panic disorder',
      'Other documented mental health conditions',
    ],
    searchTags: [
      'anxiety',
      'depress',
      'depression',
      'mental health',
      'phobia',
      'panic',
      'ptsd',
      'bipolar',
      'mood disorder',
      'psychiatric',
      'suicid',
      'self harm',
      'self-harm',
    ],
    priorityTags: ['anxiety', 'depress', 'depression', 'suicid'],
  },
];
